### ISSUE TITLE
Check that the document exists in cart

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms-cart#25]
Check that the document exists wherever it is used eg: when you are viewing your cart or requesting an order.

**Comment by robbieaverill** [comment]
I think we should check this in two places:

* When looping the contents of the cart in templates
* When updating the cart in the controller's `add` method

I think we should try and avoid checking each item exists every time the cart's getItems is called because it'll result in a lot of DB hits.

thoughts @fspringveldt?

**Comment by fspringveldt** [comment]
I think let's just leave it in the loop which displays the carts content. This way we leave the *add* method doing its sole single responsibility, and leave getItems() to do housekeeping. 

I'd keep the DB calls down by getting all Document ID's once, then doing a DataList::byIDs on it to remove all the ones which doesn't exist. (I haven't tested this yet though)

**Comment by robbieaverill** [comment]
@fspringveldt that won't fix the edge case where adding a document to cart then deleting it and viewing cart breaks.

We can check every time in getItems but implement partial caching in the template by including a hash of the item IDs or something in the cache key - that might work instead?

**Comment by fspringveldt** [comment]
Aah yes I see. Your take with caching sounds interesting yes, then it invalidates itself that way.
